name: object_detection_module
services:
  object_detection_module:
    container_name: object_detection_module
    image: ghcr.io/ad-sdl/object_detection_module
    build:
      context: .
      tags:
        - ghcr.io/ad-sdl/object_detection_module:latest
        - ghcr.io/ad-sdl/object_detection_module:dev
    privileged: true
    env_file: .env        
    volumes:
      - ./src:/home/app/object_detection_module/src
      - ./tests:/home/app/object_detection_module/tests
      - ${DEVICE}:/dev/video0
    command: python -m object_detection_module --port 2000
    
    ports:
      - 2000:2000
#####################
# WEI Core Services #
#####################
  object_detection_wei_server:
    image: ghcr.io/ad-sdl/wei
    container_name: object_detection_wei_server
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./workcells:/workcells
    command: python3 -m wei.server --workcell /workcells/test.workcell.yaml
    depends_on:
      - object_detection_wei_redis
  object_detection_wei_redis:
    image: redis
    container_name: object_detection_wei_redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
